### ISSUE TITLE
Custom Properties

### ISSUE THREAD

**Issue by fjcaetano** [mattt/GeoJSONSerialization#6]
Currently any unmapped properties are being lost, which is a shame considering JSON's flexibility on accepting any key-value pairs. Wouldn't it be interesting to use custom properties in each feature?

One approach I considered is to have an MKShape category (I believe this covers every MapKit object, but I'm not sure) to set an associated property that stores the original feature dictionary, or perhaps only the non-geoJSON properties, so it can be user in any way the developer decides.

I'm forking this repo and I'll begin to work on this since I need it now, but it's open for discussion. Please share your thoughts if you think if this is a good idea and what would be the best way to implement this.

**Comment by mattt** [comment]
Additional properties can be parsed from JSON as JSON, in conjunction with GeoJSON. I would not be particularly interested in the proposed use of associated objects to store metadata, but you're more than welcome to fork and build out to your particular use case.
